[package]
name = "prost-wkt-example"
version = "0.1.0"
authors = ["fdeantoni <fdeantoni@gmail.com>"]
edition = "2018"

[dependencies]
prost = { git = "https://github.com/fdeantoni/prost", branch = "meta" }
prost-wkt = { path = "../types" }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }

[build-dependencies]
prost-build = { git = "https://github.com/fdeantoni/prost", branch = "meta" }
