[package]
name = "prost-wkt-types"
version = "0.2.0"
authors = ["fdeantoni <fdeantoni@gmail.com>"]
license = "Apache-2.0"
repository = "https://github.com/fdeantoni/prost-wkt"
description = "Helper crate for prost to allow JSON serialization and deserialization of Well Known Types."
readme = "../README.md"
documentation = "https://docs.rs/prost-wkt"
keywords = ["protobuf", "serde", "json"]
categories = ["encoding"]
edition = "2018"

[lib]
doctest = false

[features]
default = ["std"]
std = []

[dependencies]
prost-wkt = { path = ".." }
prost = "0.9"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
chrono = { version = "0.4", features = ["serde"] }
mopa = "0.2.2"
typetag = "0.1"

[build-dependencies]
prost-wkt-build = { path = "../wkt-build" }
prost = "0.9.0"
prost-types = "0.9.0"
prost-build = "0.9"
quote = "1.0"
convert_case = "0.4"
